---
- name: Install & Start Nginx
  hosts: all
  become_user: root

  tasks:
  - name: Install nginx
    apt:
      name: nginx
      state: present

#we can also use
# shell: apt install nginx
  - name: Start nginx
    service:
      name: nginx
      state: started
